//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        public int orderid { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<int> item { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
