//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public string pname { get; set; }
        public string brand { get; set; }
        public string comment { get; set; }
        public int pid { get; set; }
        public Nullable<double> price { get; set; }
        public string pimage { get; set; }
        public Nullable<int> stoch { get; set; }
    }
}
