//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public string name { get; set; }
        public string surname { get; set; }
        public string mail { get; set; }
        public Nullable<int> roleid { get; set; }
        public int userid { get; set; }
        public string password { get; set; }
        public string phone { get; set; }
    }
}
