<%@ Page Title="" Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="UserAddOrDelete.aspx.cs" Inherits="UserAddOrDelete" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <link href="design.css" rel="stylesheet" />
    <style type="text/css">
        .auto-style1 {
            margin-left: 120px;
        }
    </style>
    </asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">

    <center>

        <h2 class="style2">
           &nbsp;&nbsp;&nbsp;&nbsp;Müşteri Kayıt</h2>
        <br />
        <br />
        <br />
        <table class="style1">
           <tr><td class="style2">
                     Ad</td>
                <td class="auto-style1">
                    <asp:TextBox ID="TextBox1" 

                    runat="server"></asp:TextBox>
                </td>
            </tr>
            <tr>
                <td class="style2">
                    SoyAd</td>
                <td>
                    <asp:TextBox ID="TextBox2" 

                    runat="server"></asp:TextBox>
                </td>
            </tr>
           <tr>
               <td class="style2">
                   Mail</td>
               <td>
                   <asp:TextBox ID="TextBox3"
                     
                    runat="server"></asp:TextBox>
               </td>
           </tr>
            <tr>
               <td class="style2">
                   Telefon</td>
               <td>
                   <asp:TextBox ID="TextBox4"
                     
                    runat="server"></asp:TextBox>
               </td>
           </tr>
            <tr>
               <td class="style2">
                   Müşteri/Satıcı</td>
               <td>
                   <asp:RadioButton ID="RadioButton1" runat="server" Text="Müşteri"/>
                   <asp:RadioButton ID="RadioButton2" runat="server" Text="Satıcı"/>

               </td>
           </tr>
            <tr>
               <td class="style2">
                   Şifre</td>
               <td>
                   <asp:TextBox ID="TextBox5"
                     
                    runat="server"></asp:TextBox>
               </td>
           </tr>
           <tr>
               <td>
                   <asp:Button ID="btnUserAdd" runat="server" OnClick="btnUserAdd_Click" Text="Kayıt Ol" />

               </td>
           </tr>
        </table>
        <asp:Label ID="Label1" runat="server" Text="Label" Visible="False"></asp:Label>
         <p>
             &nbsp;</p>
        <p>
        <asp:GridView ID="GridView1" runat="server" 

        AllowPaging="True"  DataKeyNames="userid"

            AllowSorting="True" AutoGenerateDeleteButton="True" 

            onrowdeleting="GridView1_RowDeleting" Height="221px" Width="716px" BackColor="#FFFF66" BorderColor="#3366CC" BorderStyle="Ridge" BorderWidth="1px" CellPadding="4" CssClass="fadeIn">
            <FooterStyle BackColor="#99CCCC" ForeColor="#003399" />
            <HeaderStyle BackColor="#003399" Font-Bold="True" ForeColor="#CCCCFF" />
            <PagerStyle BackColor="#99CCCC" ForeColor="#003399" HorizontalAlign="Left" />
            <RowStyle BackColor="White" ForeColor="#003399" />
            <SelectedRowStyle BackColor="#009999" Font-Bold="True" ForeColor="#CCFF99" />
            <SortedAscendingCellStyle BackColor="#EDF6F6" />
            <SortedAscendingHeaderStyle BackColor="#0D4AC4" />
            <SortedDescendingCellStyle BackColor="#D6DFDF" />
            <SortedDescendingHeaderStyle BackColor="#002876" />
        </asp:GridView>

</p>
        </center>
    <p align="right">   &nbsp;</p>
</asp:Content>

